**NUMPY'DA DİZİ OLUŞTURMA**

In [29]:
import numpy as np

#numpy.int8-numpy.int16-numpy.uint8-numpy.uint16-numpy.float32-numpy.float64 Numpy Veri Türlerindendir.

np.empty(0) #Boş bir dizi oluşturma, dizinin değeri o an ki hafızada olan rastgele değerlerden oluşmaktadır.
np.zeros(0) #İçi sıfır değerleri ile dolu bir dizi oluşturmak için kullanılır.
np.ones(1) #İçi bir değerleri ile dolu bir dizi oluşturmak için kullanılır.

shape = []
np.empty(shape,dtype=float,order='C')
np.zeros(shape,dtype=float,order='C')
np.ones(shape,dtype=float,order='C')
#shape:Dizi boyutu(satır-sütun) - dtype:Dizinin veri türü(numpy veri türü) - order:dizi elemanlarının sıralanış biçimi(hafızada nasıl saklanacağı C:satır tabanlı | F:sutun tabanlı) - return:ndarray türünde bir dizi döndürme

array(1.)

In [30]:
import numpy as np
x = np.empty([2,3],dtype=int)
print(x)

y= np.empty([3,5])
print(y)

k = np.ones(6)
print(k)

m = np.zeros([2,3,2],dtype=np.uint8)
print(m)

[[1162879424        392          0]
 [         0          1    7209071]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1.]
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


**ARRAY & ASARRAY**

In [31]:
np.array(object,dtype=None,copy=True,order='K',subok=False,ndmin=0)
# object:giriş listeleri/dizileri - dtype:liste/dizideki en küçük elemanı tutabilecek şekilde - copy:Varsayalın True çevrilecek listenin kopyasını üstüne alır 
# order:çevrilen dizinin hafızada nasıl depolanacağını belirler. - subok:geriye döndürülecek dizinin temel düzeyde olmasını sağlar varsayılan değer False
# ndmin:geriye döndürülecek dizinin en az kaç boyutlu olması gerektiğini ayarlar.Varsayılan 0'dır. - return:ndarray türünde bir dizi döndürür.

import numpy as np
pyListesi = [1,2,3]

x = np.array(pyListesi)
print(x)

y = np.array([[3,5],[2,6]])
print(y)

z = np.array([1,2,3], ndmin=2)
print(z)

[1 2 3]
[[3 5]
 [2 6]]
[[1 2 3]]


In [32]:
import numpy as np
a = [1,0]
np.asarray(a,dtype=None,order=None)
# a:giriş listeleri/dizileri - dtype:liste/dizideki en küçük elemanı tutabilecek şekilde - order:sadece sütun tabanlı'C' ve satır tabanlı'F' varsayılan olarak alınabilir.

def asarray(a,dtype=None,order=None):
    return array(a,dtype,copy=False,order=order)
# asarray aynı array fonksiyonu gibi çağrılır tek farkı copy parametresini FALSE olarak çağrılmasıdır yani kopya sadece ilgili nesnenin kendisinde olabilecek bir metoda bağlı olacaktı.

import numpy as np
x = np.ones(2)
print(x)

np.array(x)[1] = 2
print(x)

np.asarray(x)[1] = 2
print(x)

[1. 1.]
[1. 1.]
[1. 2.]


**ARANGE()**

In [38]:
#Belirtilen eşit aralıklarda bir dizi oluşturmayı sağlar. Oluşan dizi tek boyutludur. Gerekli durumlarda dizi değiştirilebilir. range() benzer!
import numpy as np
start=5
stop=16
step=3
np.arange(start, stop, step, dtype=None)
# start:ilk değer/başlangıç değeri ayarlanır varsayalın değeri 0'dır. - stop:son değer/bitiş değeri ayarlanır(yazılan değer dahil değildir).
# step:adım değeridir,başlangıç değerinden sonra hangi aralıklar ile artırılıp azaltılacağı(varsayılan değeri:1) - dtype:veri türü ayarı
import numpy as np
x = np.arange(5)
print(x)

y = np.arange(5,16,3,dtype=np.uint8)
print(y)

z = np.arange(20,16,-1)
print(z)

[0 1 2 3 4]
[ 5  8 11 14]
[20 19 18 17]


**RANDOM()**

In [92]:
# np.random() çalışma mantığı ones ile zeros ile aynıdır farkı doldurulan dizileri rastgele üretir. !Parametre alacağı değerler ile bir dizi üretmesi sağlanabilir. **Seed Value** 
import numpy as np
low=0
high=5
size=6
np.random.randint(low, high=high, size=size, dtype=int)
# low:ilk başlangıç değeridir,verilmez ise ilk başlangıç değerini high olarak kabul edilir. - high:rastgele değer üretiminde olabilecek en değeri belirlemek için kullanılır.(buraya yazılan değer dahil değildir.)
# size:dizinin boyut bilgisi(varsayılan 1) - dtype:veri türü ayarı - return:geriye int(tam sayı değeri) döndürür.

import numpy as np 
x = np.random.randint(0,5,size=6)
print(x)

y = np.random.randint(0,5,size=(3,2))
print(y)

z = np.random.randint(20,size=5)
print(z)

t = np.random.randint(1,[6,8,10])
print(t)

np.random.rand(0,1)  #parametre olarak boyut verilir ve tüm diziyi 0-1 arası düzgün dağıtılmış rastgele sayılarla doldurulur.
np.random.randn(0,1) #parametre olarak boyut verilir ve tüm diziyi 0-1 arası normal dağıtılmış rastgele sayılarla doldurulur.
np.random.random_sample() #0-1 arasında rastgele sayı verir.
np.random.seed()     #rastgele sayı üretme moturunu bir besleyerek hep aynı sırada sayı üretmesini sağlar.

[0 4 3 1 3 3]
[[1 0]
 [1 2]
 [4 4]]
[ 1  2  1 12 18]
[5 5 1]


**LİNSPACE()**

In [99]:
# np.linspace() çalışma mantığı arange ile benzer.Farklı olarak başlangıç ve bitiş sayılarından istenen miktar kadar eşit miktarda aralık ile oluşturulmuş dizi oluşturmak için kullanılır.
import numpy as np
start=0
stop=1
num=50
endpoint=True
retstep=False
dtype=np.uint8
axis=0
np.linspace(start,stop,num,endpoint,retstep,dtype,axis)
# start:aralığın başlangıç değeri - stop:aralığın bitiş değeri(bitiş değeri dahil) - num:başlangıç ve bitiş değeri arasında toplamda kaç eleman ile oluşacağını belirtir(varsayılan 50)
# endpoint:eğer false ayarlanırsa bitiş değeri diziye dahil edilmez(varsayılan TRUE) - retstep:eğer true ayarlanırsa oluşturulan dizi ile birlikte elemanlar arası farkın kaç olduğu bilgisinide döndürür.(varsayılan FALSE)
# dtype:numpy veri türü ayarlaması - axis:sadece başlangıç/bitiş değerleri dizi şeklinde ise kullanılır. -1 verilir ise en sonda bir sonuç ekseni üretilir.(varsayılan 0)

import numpy as np
x = np.linspace(5,10,3)
print(x)

y = np.linspace(3.0,5.0,num=5,endpoint=False)
print(y)

z = np.linspace(3.0,5.0,num=5,retstep=True)
print(z)

[ 5.   7.5 10. ]
[3.  3.4 3.8 4.2 4.6]
(array([3. , 3.5, 4. , 4.5, 5. ]), 0.5)


**Bazı fonksiyon/metotların iki çeşit kullanımı mevcuttur. Birisi direkt mevcut dizi üzerinde metot olarak çağrılarak, diğeri NumPy paketinin bir fonksiyonu olarak çağrılarak kullanılabilir.
Kullanımlarının tek farkı birisinde üzerinde çalışılacak dizinin parametre olarak sağlanması diğerinde ise direkt ilgili dizi üzerinde çalıştırılmasıdır.**

**DİZİLERDE ÖZNİTELİK ÇIKARIMI**

In [103]:
import numpy as np
a = np.array([[1,1],[0,0],
              [1,0],[0,1],
              [0,1],[1,0]],dtype=np.int8)

ndarray.ndim()#dizinin kaç boyut olduğunu döndürür.
np.ndim(a) 

ndarray.size #toplamda kaç eleman olduğunu döndürür.
np.size(a,axis=None)

np.shape(a) #bir dizinin kaç boyutu olduğunun yanı sıra her boyutunda kaç eleamn olduğunu döndürür.

ndarray.itemsize #byte cinsinden uzunluğunu verir.
ndarray.flags #bayraklar olarak gruplanan ve dizi için programlama dilleri prensipleriymiş gibi veren nitelikler bulunur.

np.max(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
ndarray.max(axis=None,out=None,keepdims=False,initial=<no value>,where=True)

np.min(a,axis=None,out=None,keepdims=<no value>,initial=<no value>,where=<no value>)
ndarray.min(axis=None,out=None,keepdims=False,initial=<no value>,where=True)

np.argmin(a,axis=None,out=None) 
ndarray.argmin(a,axis=None,out=None)#en küçük değerinin indeks numarasını bulmak 

np.argmax(a,axis=None,out=None) 
ndarray.argmax(a,axis=None,out=None)#en büyük değerinin indeks numarasını bulmak

np.mean(a,axis=None,out=None,dtype=None,keepdims=<no value>)
ndarray.mean(a,axis=None,out=None,dtype=None,keepdims=False) #dizinin ortalamasını geri dönderir.

np.prod(a, axis=None, out=None, keepdims=<no value>, initial=<no value>,where=<no value>)
ndarray.prod(a,axis=None,out=None,keepdims=False,initial=<no value>,where=True) #dizi elemanlarının çarpımını verir.

# a:üzerinde çalışılacak dizi - axis:üzerinde çalışılacak eksen bilgilerini sağlanarak sadece istenen eksenlerde sonuçlar alınabilir(varsayılan None) 
# out:sonucun farklı bir dizide gösterilebilmesi için ndarray dizisinde verilebilir(varsayılan None) - keepdims:TRUE çıkşta elde edilecek değerin giriş değerin giriş dizisi boyutlarına uygun olması için(FALSE)
# where:FALSE ayarlanırsa bitiş değeri dizi'ye dahil edilmez.(Varsayılan TRUE)

import numpy as np

x = np.array([[0,1],[2,3],
              [0,1],[2,3],
              [0,1],[2,8]],dtype=np.int8)
print(x.ndim)
print("********")
print(x.size)
print("********")
print(x.shape)
print("********")
print(x.itemsize)
print("********")
print(x.flags)
print("********")

y = np.random.randint(0,20,10)
print(y)
print("********")
print(y.max())
print(y.argmax())
print("********")
print(y.min())
print(y.argmin())
print("********")
print(y.mean())
print(y.prod())
print("********")


2
********
12
********
(6, 2)
********
1
********
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

********
[7 3 6 6 6 4 3 6 2 1]
********
7
0
********
1
9
********
4.4
653184
********


**DİZİLERİ YENİDEN BOYUTLANDIRMA VE BİÇİM DEĞİŞTİRME** 

In [123]:
import numpy as np
ndarray.reshape(shape,order='C') 
# eleman değerini değitirmeden dizileri yeniden boyutlandırmak için kullanılır. !Dizinin boyutu değiştirirken eleman sayısı eski boyut ile aynı eleman sayısı olmasına özen gösterilmeli.
np.reshape(a,newshape,order='C')
# shape:yeni boyut girilir. - order:sadece 'F' ve 'C' değerlerini alır - return:geriye boyutu verilen parametrelere göre ayarlanmış bir dizi döndürür.- a:yeniden boyutlandırılacak dizi

import numpy as np 
x = np.arange(6)
print(x.reshape(2,3))
print(np.reshape(x,(3,2)))

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


**reshape() fonksiyonundan sonra kullanılacak BASE metodu ile dizinin hafıza da kendi yerinde mi sahip olduğu veya bir kopya mı olduğunu görebilir.**

**Eğer bir dizi kendine ait veriler ile kurulmuşsa BASE metodu NONE şeklinde dönüş yapacaktır.**

**Eğer başka bir dizinin kopyası ise kendi orjinal haline dönüşecektir.**

In [111]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr.base is arr)

True


In [146]:
import numpy as np
new_shape = 3
ndarray.resize(new_shape, refcheck=True) #çalıştığı dizinin orjinal halini değiştirir.
np.resize(a , new_shape)
# new_shape:yeni boyut - refcheck:FALSE,referans kontrol edilmeyecektir. Boş bıraklırsa farklı bir nesneye referans gösterilip/gösterilmediği kontrol edilir.

import numpy as np
x = np.array([[1,2,3],[8,9,10]])
x.resize((3,2))
print(x)


[[ 1  2]
 [ 3  8]
 [ 9 10]]


In [145]:
ndarray.flatten(order='C') #dizinin bir boyutta daraltılmış yeni bir kopyasını geriye döndürür.(Düzleştirme)
ndarray.flat(indeks) #diziyi bir boyuta indirgemeden sadece dizi daraltılmış olsaydı şekline göre istenen indeks numaralı verisini gönderir.
ndarray.ravel() #orjinal verinin tek boyutta daraltılmış haline return ile geriye dönderir.

import numpy as np
x = np.arange(10).reshape(5,2)
print(x)

print(x.flatten())

print(x.flat[2])

print(x.ravel())
x.ravel()[2] = 100

print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]
2
[0 1 2 3 4 5 6 7 8 9]
[[  0   1]
 [100   3]
 [  4   5]
 [  6   7]
 [  8   9]]


In [150]:
import numpy as np
ndarray.transpose(*axes)  #üzerinde çalışılacak aksis bilgilerini parametre olarak alabilmesidir.
np.transpose(a,axes=None) 
ndarray.T #T fonksiyonu parametre almadan çalışabilir.

import numpy as np
x = np.array([[2,3,2,5],[6,8,2,8]])

print(x.transpose())

print(x.T)

print(x)

#Her iki satırda da orjinal veriye etki etmediği gözlemlenilmiştir.

[[2 6]
 [3 8]
 [2 2]
 [5 8]]
[[2 6]
 [3 8]
 [2 2]
 [5 8]]
[[2 3 2 5]
 [6 8 2 8]]


In [164]:
np.flip(m, axis=None) #parametre olarak almış olduğu eleman dizilerini tersten sokar
# m:sıralanacak dizi - axis:eğer bir değer verilmezse tüm eksenlerde olan elemanları tersten yazdırır.

import numpy as np

x = np.array([[1,2,3],[8,9,10],[15,16,17]])
print(x)

print(np.flip(x))

print(np.flip(x,0)) #sadece satırları ters çevirerek ekrana yazdırdı.

print(np.flip(x,1)) #sadece sütunları ters çevirerek ekrana yazdırdı.

print(np.flip(x[2])) #sadece dizinin ikinci satırını ters çevirerek ekrana yazdırdı.

print(np.flip(x[:,2])) #sadece dizinin ikinci sütununu ters çevirerek ekrana yazdırdı.

[[ 1  2  3]
 [ 8  9 10]
 [15 16 17]]
[[17 16 15]
 [10  9  8]
 [ 3  2  1]]
[[15 16 17]
 [ 8  9 10]
 [ 1  2  3]]
[[ 3  2  1]
 [10  9  8]
 [17 16 15]]
[17 16 15]
[17 10  3]


***DİZİLERDE SIRALAMA - ARAMA - SAYMA - EKLEME - ÇIKARMA***

In [168]:
np.sort(a,axis=-1,kind=None,order=None) #elemanların değerlerine göre sıralama yapar.
# a:sıralamak dizi verilir. - axis:dizilerin sıralanmadan önce düzgünleştirip/düzgünleştirilmeyeceğini ayarlamak için kullanılır.(varsayılan -1)
# kind:notasyonlardan birisini alır.

import numpy as np

x = np.array([5,10,8])
print(x)
print(np.sort(x))

y = np.array([[1,5],[9,3]])
print(np.sort(y,axis=None))

print(np.sort(y,axis=0))  #dizi sıralanmadan önce düzgünleştirilmedi

print(np.sort(y,axis=-1)) #dizi sıralanmadan önce düzgünleştirildi

[ 5 10  8]
[ 5  8 10]
[1 3 5 9]
[[1 3]
 [9 5]]
[[1 5]
 [3 9]]


In [178]:
np.unique(a,return_index=False,return_inverse=False,return_counts=False,axis=None)
# return_index:TRUE bulunan benzersiz değerlerin indeks numarasını da geriye dönderir.(varsayılan FALSE) - return_inverse:TRUE dizideki her bir elemanın arama listesi sonucunda hangi indeks numarasında olduğu bilgisini geriye dönderir.(varsayılan FALSE)
# return_counts:TRUE bulunan benzersiz eleman sayısını da geriye dönderir.(varsayılan FALSE) - axis:sadece o eksende çalışır.

import numpy as np
x = np.array([2,3,2,5,6,8,2,8])
print(np.unique(x))
print(np.unique(x,return_inverse=True))
print(np.unique(x,return_index=True))
print(np.unique(x,return_counts=True))
print(np.unique(x,axis=-1))

[2 3 5 6 8]
(array([2, 3, 5, 6, 8]), array([0, 1, 0, 2, 3, 4, 0, 4], dtype=int64))
(array([2, 3, 5, 6, 8]), array([0, 1, 3, 4, 5], dtype=int64))
(array([2, 3, 5, 6, 8]), array([3, 1, 1, 1, 2], dtype=int64))
[2 3 5 6 8]


In [185]:
values = 1
np.append(a,values,axis=None)

import numpy as np
x = np.array([[1,2],[5,6]])
print(np.append(x,[5,6]))
print(np.append(x,[[9,10]],axis=0))
print(np.append(x,[[20,21],[22,23]],axis=0))
print(np.append(x,[[20],[23]],axis=1))

[1 2 5 6 5 6]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 1  2]
 [ 5  6]
 [20 21]
 [22 23]]
[[ 1  2 20]
 [ 5  6 23]]


In [192]:
obj=1
values=100
np.insert(a,obj,values,axis=None)

import numpy as np 
x = np.array([[1,2],[5,6]])
print(np.insert(x,1,100))
print(np.insert(x,1,100,axis=1))
print(np.insert(x,2,[[100],[101],[102]],axis=1))
print(np.insert(x,1,[[100,101]],axis=0))

[  1 100   2   5   6]
[[  1 100   2]
 [  5 100   6]]
[[  1   2 100 101 102]
 [  5   6 100 101 102]]
[[  1   2]
 [100 101]
 [  5   6]]


In [195]:
np.delete(a,obj,axis=None)

import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print(np.delete(x,2))
print(np.delete(x,1,axis=1))
print(np.delete(x,0,axis=0))

[1 2 4 5 6]
[[1 3]
 [4 6]]
[[4 5 6]]


***DİZİLERİ BİRLEŞTİRME VE PARÇALAMA***

In [14]:
import numpy as np
np.concatenate((a1,a2),axis=0,out=None) #parametre olarak aldığı dizileri eksen olarak aldığı bilgiye göre birleştirme 
# a1,a2:dizileri verir,boyutları ve axis'leri birbirlerine uygun olması şarttır. - axis:NONE işleminden önce düzleştirme işlemi yapılır(varsayılan 0)(0 satır - 1 sütun)
# out:parametre olarak verilen dizinin,birleştirilmiş ile boyut/biçim olarak uygun olmalı

import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])
z = np.array([[1,2,3]])

xy = np.concatenate((x,y),axis=0)
print(xy)

print(np.concatenate((x,y),axis=None))

print(np.concatenate((xy,z.T),axis=1))

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 2 1]
 [3 4 2]
 [5 6 3]]


In [22]:
np.stacks(arrays,axis=0,out=None) #parametre olarak aldığı dizileri eksen olarak aldığı bilgiye göre birbirine ekler.Dizinin orjinal üzerinde çalışmaz,kopyası üzerinde çalışır.
# axis:0 ilk boyut | -1 son boyut

import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.stack((x,y),axis=0))
print(np.stack((x,y),axis=-1))

print("**********************")

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.stack((a,b),axis=0))
print(np.stack((a,b),axis=-1))
print(np.stack((a,b),axis=1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
**********************
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [30]:
np.vstack(tup) #vertical(dikey) ekseninde parametre olarak sadece birleşecek dizileri alır.
np.hstack(tup) #horizontal(yatay) ekseninde parametre olarak sadece birleşecek dizileri alır.
# tup:Birleştirilecek diziler verilir.Dizilerin uygun boyutlarda olması gerekmektedir.

import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.vstack((x,y)))
print(np.hstack((x,y)))

print("**************")

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
**************
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [37]:
np.split(ary,indices_or_sections,axis=0) #Orijinal olmayan kopya olan dizileri parametre alarak ayırma işlemidir.Görüntü oluşturur.
np.vsplit(ary,indices_or_sections) #vertical(dikey) ekseninde parametre olarak sadece ayrılacak dizileri alır. axis=0
np.hsplit(ary,indices_or_sections) #horizontal(yatay) ekseninde parametre olarak sadece ayrılacak dizileri alır. axis=1
# indices_or_sections:Dizinin kaç parçaya ayrılacağı bilgisi verilir.Eleman sayısı ile dizinin kaç parça sayısı tam bölünebilir olmalıdır.
#                     Eğer eşit bölme olmayacaksa [a,b,c..] şeklinde liste parametre olarak sağlanabilir.Artan sayısal parametrelere göre parçalama yapılır.

import numpy as np
x = np.arange(9.0)
print(np.split(x,3))
print(np.split(x,[2,5,7]))

y = np.arange(16.0).reshape(4,4)
print(y)
print(np.vsplit(y,2)) #print(np.split(y,2,axis=0))
print(np.hsplit(y,2)) #print(np.split(y,2,axis=1))

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]
[array([0., 1.]), array([2., 3., 4.]), array([5., 6.]), array([7., 8.])]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


**INDEKSLEME FILTRELEME VE ERİŞİM**


Indeksleme yöntemleriyle büyük bir dizinin içerisinden amacımıza hizmet edecek bir bölümü dışarıya almaktadır.Aksi bir ifade bulunmadıkça dizinin orjinali değişmemekte dizinin kopysdı alınmamaktadır. 
Gösterilmiş şekli saklanılmak isteniliyorsa değişkene atanabilir.
 Indeksleme :(aralık) ->
     a:b(a numaralı indeks elemanında b numaralı indeks elemanına kadar) , 
     :b(ilk elemandan b numaralı indeks elemanına kadar), 
     a:(a numaralı indeks elemanından dizinin sonuna kadar),
     :(bütün elemanlar), 
     a::x(a indeksinden başlayan her x.'inci indekse ulaşır.)
     
**NUMPY C-ORDER INDEXING yöntemiyle dizileri hafıza alanında saklamaktadır.Bunun anlamı en son eklenen indeksli elemanlar en çok değişen ve kolay ulaşılabilen hafıza alanında saklanmaktadır.**

In [57]:
import numpy as np
x = np.arange(5.0)*2
y = np.arange(25.0).reshape(5,5)

print(x)
print(x[3])
print(x[3].shape)

print("********")

print(y)
print(y[1].shape)
print(y[3,2])
print(y[1])

print("*********")
print(x[1:3])
print(y[1:3])
print(x[np.array([4,2,1])])
print(y[3:5,2:4]) #satır,sutun kesısen yerler.
print(y[:,1:3]) #satur,sutun kesısen yerler
print(y[:2,3:]) #satır,sutun kesısen yerler
print(y[4,1::3]) #satır,sutun kesısen yerler
print(y[::2,0]) #2'şer indeks artırımda satır bazlı

[0. 2. 4. 6. 8.]
6.0
()
********
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
(5,)
17.0
[5. 6. 7. 8. 9.]
*********
[2. 4.]
[[ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
[8. 4. 2.]
[[17. 18.]
 [22. 23.]]
[[ 1.  2.]
 [ 6.  7.]
 [11. 12.]
 [16. 17.]
 [21. 22.]]
[[3. 4.]
 [8. 9.]]
[21. 24.]
[ 0. 10. 20.]


**SLICE() == : 'dır. NUMPY'da**

In [67]:
start = 0
stop = 5
step = 1
a[start:stop:step]
# a:üzerinde çalışılacak dizi. - start:başlangıç indeks numarası(varsayılan 0) - stop:alınacak en son indeks numarası verilir(burada verilen değer dahil değil) - step:elemanların hangi adımlarla seçileceği(1)

import numpy as np
x = np.arange(10.0)
print(x)
print(x[slice(3,8,2)])

parca = slice(3,8,2)
print(x[parca])
print(x[3:8:2])

#!Gosterım amaçlıdır, dizinin orijinaş yapısı etkilenmez.

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[3. 5. 7.]
[3. 5. 7.]
[3. 5. 7.]


**MANTIKSAL OPERATÖRLER İLE FİLTRELEME - INDEKSLEME**

In [78]:
#! Dizideki elemanlar indeks numaralarına göre değil içeriklerinin belirli şartları sağlama durumlarına göre seçilmelidir.IF şart cümleciği güzel olur.Geriye dönen dizinin tek boyutta indirgenmiş olmalı.
#! AND OR yeribe &  | kullanılmalı NUMPY'da.

import numpy as np
x = np.array([17,54,8,10,49,79,30,78,84])
y = np.reshape(x,(3,3))

print(x)
print(np.sort(x))
print(y)

print(x[x>50])
print(y[(y>30) & (y<50)])
print((y>30) & (y<50))

[17 54  8 10 49 79 30 78 84]
[ 8 10 17 30 49 54 78 79 84]
[[17 54  8]
 [10 49 79]
 [30 78 84]]
[54 79 78 84]
[49]
[[False False False]
 [False  True False]
 [False False False]]


**BİTWİSE OPERATÖRLERİ: görüntü işlemede MASKELEME yöntemleri için kullanılır. (and/or/xor/not/shift) Bit seviyesi işlemlerdir.**

In [10]:
import numpy as np

X=10
Y=12

a=np.array([6,5])
b=np.array([8,9])
e=np.array([[86],[93],[128]])
f=np.array([[0],[255],[0]])

print(np.bitwise_and(X,Y))
print(np.bitwise_or(X,Y))
print(np.bitwise_xor(X,Y))

print(np.bitwise_and(a,b))
print(np.bitwise_and(e,f))

print(np.left_shift(10,2))
print(np.right_shift(10,2))

8
14
6
[0 1]
[[ 0]
 [93]
 [ 0]]
40
2


**FARKLI BOYUTLU DİZİLERDE İŞLEMLER(BROADCASTİNG)**

**Büyük bir dizi ile küçük bir dizinin aritmetik işlemlerde yayılmadan kasıt küçük dizi değiştirilmeden büyük dizi işlemlerinde uygulanılması veya yayılmasıdır.
Diziler eişit boyda olmalı.**

**DİZİLERDE KARŞILAŞTIRMA İŞLEMLERİ**

In [16]:
minimum(x1,x2,out=None,where=True,casting='same_kind',order='K',dtype=None,subok=[True,signature,extobj])
maximum(x1,x2,out=None,where=True,casting='same_kind',order='K',dtype=None,subok=[True,signature,extobj])
# x1,x2:karşılaştırma yapılacak diziler.(Diziler eşit boyutta değil ise BROADCASTİNG yap) - out:None geriye giriş ile aynı boyutta yeni bir dizi döndürür - 
# where:bir dizi verilebilir.TRUE,universal function durumunu döndürür.FALSE,out dizisi olduğu gibi bırakılır.(varsayılan TRUE)
# casting:sonuç dizisinin dönüşümü için kullanılır.Ayarlama yapılmaz ise giriş dizisiyle aynı olacaktır.(varsayılan same_kind)

import numpy as np
x = np.minimum([6,5,3],[5,6,8])
y = np.maximum([6,5,3],[5,6,8])
z = np.minimum([[6,5,3],[5,6,8]],[2,9,1]) #broadcasting
t = np.minimum([5.,3.],[2.,7.],where=[True,False])

print(x)
print(y)
print(z)
print(t)



[5 5 3]
[6 6 8]
[[2 5 1]
 [2 6 1]]
[2.00000000e+000 4.24399158e-314]


In [18]:
np.clip(a,a_min,a_max,out=None,**kwargs) #parametre olarak aldığı diziyi kendisine verilen minimum ve maksimum limit değerlerine göre düzenler ve geriye düzenlemiş olduğu verilerle oluşturulan yeni bir dizi döndürür.

import numpy as np
a = np.array([6,5,3,9,2])

x = np.clip(a,3,5)
y = np.clip(a,4,None,out=a)

print(x)
print(a)

[5 5 3 5 3]
[6 5 4 9 4]


In [20]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [22]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (c

In [24]:
a = np.array([1,2,3,4,5])
a?

Type:        ndarray
String form: [1 2 3 4 5]
Length:      5
File:        c:\users\emred\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object th

**PANDAS**

In [26]:
import pandas as pd 
pd.DataFrame(data=None,index=None,columns=None,dtype=None,copy=False)
# data:ndarray,list,dict vb. veri türleri girdi olarak verilir. -- index:satır başlarına yazılacak etiketleri ayarlamak için kullanılır. -- columns:sütun başlarına yazılacak etiketleri ayarlamak için kullanılır
df.to_csv() # .csv haricinde sql,excel,html,json,sql,string gibi bir çok format desteklenir.

NameError: name 'df' is not defined

In [28]:
#PANDAS İLE VERİ SETİ KAYIT ETMEK
import numpy as np
import pandas as pd

bilgiler = np.array([
['Ahmet','1984'],
['Mehmet','1986'],
['Ali','1999'],
['Osman','1987'],
['Enes','1963']])

df = pd.DataFrame(data=bilgiler,columns=['isim','dTarihi'])
print(df)
print("************")
print(df.loc[1])

df.to_csv('bilgi.csv')

     isim dTarihi
0   Ahmet    1984
1  Mehmet    1986
2     Ali    1999
3   Osman    1987
4    Enes    1963
************
isim       Mehmet
dTarihi      1986
Name: 1, dtype: object


In [30]:
#PANDAS İLE VERİ SETİ ÇEKME
import pandas as pd
import numpy  as np

df = pd.read_csv('bilgi.csv')
print(df)
print(df.loc[1]) #sadece 1 indeksli satıra ulaşma

   Unnamed: 0    isim  dTarihi
0           0   Ahmet     1984
1           1  Mehmet     1986
2           2     Ali     1999
3           3   Osman     1987
4           4    Enes     1963
Unnamed: 0         1
isim          Mehmet
dTarihi         1986
Name: 1, dtype: object


**GÖRÜNTÜLER ÜZERİNDE ÇALIŞMAK BİR NEVİ DİZİLER ÜZERİNDE ÇALIŞMAK GİBİDİR**
                                                   ~ **EREN TAŞ**